araali:
  workload-id:
  zone: ""
  tenant-id: ""
  agent-name: ""
  image: "quay.io/araalinetworks/araaliagent:prod"
  log-level: "INFO"
  backend: "prod.aws.araalinetworks.com"
  mem: "false"
  k8s-req-cpu: "50m"
  k8s-limits-cpu: "100m"
  k8s-req-mem: "128Mi"
  k8s-limits-mem: "256Mi"
