araali:
  workload-id:
  zone: ""
  tenant-id: ""
  agent-name: ""
  image: "175118736976.dkr.ecr.us-west-2.amazonaws.com/araali/araali-agent:latest"
  log-level: "INFO"
  backend: "prod.aws.araalinetworks.com"
